name: Build PiMesh

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   # x86-64 runner
    steps:
      - uses: actions/checkout@v4

      - name: Pull ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/bcm27xx/bcm2710/openwrt-imagebuilder-23.05.3-bcm27xx-bcm2710.Linux-x86_64.tar.xz
          tar -xJf openwrt-imagebuilder-23.05.3-bcm27xx-bcm2710.Linux-x86_64.tar.xz

      - name: Build image
        run: |
          cd openwrt-imagebuilder-23.05.3-bcm27xx-bcm2710.Linux-x86_64
          make image PROFILE="rpi-3" FILES="../files" \
            PACKAGES="kmod-batman-adv batctl alfred avahi-daemon odhcpd-ipv6only iperf3 \
            tcpdump-full kmod-usb-net kmod-usb-net-rtl8152 wpad-mesh-openssl"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PiMesh-img
          path: |
            openwrt-imagebuilder-23.05.3-bcm27xx-bcm2710.Linux-x86_64/bin/targets/bcm27xx/bcm2710/*.img.gz
