name: Build OpenWrt Mesh Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Prepare build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk \
          git ccache gettext libssl-dev xsltproc wget python3 rsync unzip file

    - name: Cache OpenWrt downloads
      uses: actions/cache@v4
      with:
        path: openwrt/dl
        key: openwrt-dl-${{ hashFiles('.config') }}
        restore-keys: |
          openwrt-dl-

    - name: Run build script
      run: |
        chmod +x build-ib.sh
        ./build-ib.sh

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-mesh-image
        path: output/*rpi-3*-sysupgrade.img*
